In [1]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
import numpy as np


In [4]:
xy = np.loadtxt('./data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [5]:
# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)


In [7]:
tf.model = tf.keras.Sequential()

In [8]:
# activation function doesn't have to be added as a separate layer. Add it as an argument of Dense() layer
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=3, activation='linear'))

In [9]:
# tf.model.add(tf.keras.layers.Activation('linear'))
tf.model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [11]:
tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(learning_rate=1e-5))

In [13]:
history = tf.model.fit(x_data, y_data, epochs=2000)

Epoch 1/2000
1/1 [==============================] - 0s 5ms/step - loss: 16.1628
Epoch 2/2000
1/1 [==============================] - 0s 4ms/step - loss: 16.1568
Epoch 3/2000
1/1 [==============================] - 0s 5ms/step - loss: 16.1508
Epoch 4/2000
1/1 [==============================] - 0s 4ms/step - loss: 16.1448
Epoch 5/2000
1/1 [==============================] - 0s 4ms/step - loss: 16.1388
Epoch 6/2000
1/1 [==============================] - 0s 4ms/step - loss: 16.1328
Epoch 7/2000
1/1 [==============================] - 0s 5ms/step - loss: 16.1269
Epoch 8/2000
1/1 [==============================] - 0s 3ms/step - loss: 16.1209
Epoch 9/2000
1/1 [==============================] - 0s 4ms/step - loss: 16.1149
Epoch 10/2000
1/1 [==============================] - 0s 4ms/step - loss: 16.1089
Epoch 11/2000
1/1 [==============================] - 0s 3ms/step - loss: 16.1029
Epoch 12/2000
1/1 [==============================] - 0s 5ms/step - loss: 16.0970
Epoch 13/2000
1/1 [==================

1/1 [==============================] - 0s 6ms/step - loss: 15.5755
Epoch 103/2000
1/1 [==============================] - 0s 4ms/step - loss: 15.5699
Epoch 104/2000
1/1 [==============================] - 0s 4ms/step - loss: 15.5643
Epoch 105/2000
1/1 [==============================] - 0s 4ms/step - loss: 15.5586
Epoch 106/2000
1/1 [==============================] - 0s 4ms/step - loss: 15.5530
Epoch 107/2000
1/1 [==============================] - 0s 4ms/step - loss: 15.5474
Epoch 108/2000
1/1 [==============================] - 0s 4ms/step - loss: 15.5418
Epoch 109/2000
1/1 [==============================] - 0s 4ms/step - loss: 15.5362
Epoch 110/2000
1/1 [==============================] - 0s 4ms/step - loss: 15.5306
Epoch 111/2000
1/1 [==============================] - 0s 4ms/step - loss: 15.5250
Epoch 112/2000
1/1 [==============================] - 0s 4ms/step - loss: 15.5194
Epoch 113/2000
1/1 [==============================] - 0s 4ms/step - loss: 15.5138
Epoch 114/2000
1/1 [===========

1/1 [==============================] - 0s 4ms/step - loss: 15.0303
Epoch 203/2000
1/1 [==============================] - 0s 3ms/step - loss: 15.0250
Epoch 204/2000
1/1 [==============================] - 0s 3ms/step - loss: 15.0197
Epoch 205/2000
1/1 [==============================] - 0s 3ms/step - loss: 15.0144
Epoch 206/2000
1/1 [==============================] - 0s 3ms/step - loss: 15.0092
Epoch 207/2000
1/1 [==============================] - 0s 3ms/step - loss: 15.0039
Epoch 208/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.9986
Epoch 209/2000
1/1 [==============================] - 0s 4ms/step - loss: 14.9934
Epoch 210/2000
1/1 [==============================] - 0s 4ms/step - loss: 14.9881
Epoch 211/2000
1/1 [==============================] - 0s 4ms/step - loss: 14.9829
Epoch 212/2000
1/1 [==============================] - 0s 4ms/step - loss: 14.9776
Epoch 213/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.9724
Epoch 214/2000
1/1 [===========

1/1 [==============================] - 0s 3ms/step - loss: 14.5187
Epoch 303/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.5138
Epoch 304/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.5088
Epoch 305/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.5039
Epoch 306/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.4989
Epoch 307/2000
1/1 [==============================] - 0s 4ms/step - loss: 14.4940
Epoch 308/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.4890
Epoch 309/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.4841
Epoch 310/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.4792
Epoch 311/2000
1/1 [==============================] - 0s 5ms/step - loss: 14.4742
Epoch 312/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.4693
Epoch 313/2000
1/1 [==============================] - 0s 4ms/step - loss: 14.4644
Epoch 314/2000
1/1 [===========

1/1 [==============================] - 0s 3ms/step - loss: 14.0386
Epoch 403/2000
1/1 [==============================] - 0s 4ms/step - loss: 14.0339
Epoch 404/2000
1/1 [==============================] - 0s 4ms/step - loss: 14.0293
Epoch 405/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.0246
Epoch 406/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.0200
Epoch 407/2000
1/1 [==============================] - 0s 4ms/step - loss: 14.0154
Epoch 408/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.0107
Epoch 409/2000
1/1 [==============================] - 0s 4ms/step - loss: 14.0061
Epoch 410/2000
1/1 [==============================] - 0s 4ms/step - loss: 14.0014
Epoch 411/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.9968
Epoch 412/2000
1/1 [==============================] - 0s 4ms/step - loss: 13.9922
Epoch 413/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.9876
Epoch 414/2000
1/1 [===========

1/1 [==============================] - 0s 3ms/step - loss: 13.5878
Epoch 503/2000
1/1 [==============================] - 0s 4ms/step - loss: 13.5834
Epoch 504/2000
1/1 [==============================] - 0s 4ms/step - loss: 13.5790
Epoch 505/2000
1/1 [==============================] - 0s 4ms/step - loss: 13.5747
Epoch 506/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.5703
Epoch 507/2000
1/1 [==============================] - 0s 4ms/step - loss: 13.5660
Epoch 508/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.5616
Epoch 509/2000
1/1 [==============================] - 0s 4ms/step - loss: 13.5573
Epoch 510/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.5529
Epoch 511/2000
1/1 [==============================] - 0s 4ms/step - loss: 13.5486
Epoch 512/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.5442
Epoch 513/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.5399
Epoch 514/2000
1/1 [===========

1/1 [==============================] - 0s 3ms/step - loss: 13.1644
Epoch 603/2000
1/1 [==============================] - 0s 4ms/step - loss: 13.1603
Epoch 604/2000
1/1 [==============================] - 0s 4ms/step - loss: 13.1562
Epoch 605/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.1521
Epoch 606/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.1480
Epoch 607/2000
1/1 [==============================] - 0s 4ms/step - loss: 13.1439
Epoch 608/2000
1/1 [==============================] - 0s 4ms/step - loss: 13.1398
Epoch 609/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.1357
Epoch 610/2000
1/1 [==============================] - 0s 4ms/step - loss: 13.1316
Epoch 611/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.1275
Epoch 612/2000
1/1 [==============================] - 0s 4ms/step - loss: 13.1235
Epoch 613/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.1194
Epoch 614/2000
1/1 [===========

1/1 [==============================] - 0s 4ms/step - loss: 12.7666
Epoch 703/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.7627
Epoch 704/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.7589
Epoch 705/2000
1/1 [==============================] - 0s 4ms/step - loss: 12.7550
Epoch 706/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.7512
Epoch 707/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.7473
Epoch 708/2000
1/1 [==============================] - 0s 4ms/step - loss: 12.7435
Epoch 709/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.7396
Epoch 710/2000
1/1 [==============================] - 0s 4ms/step - loss: 12.7358
Epoch 711/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.7320
Epoch 712/2000
1/1 [==============================] - 0s 4ms/step - loss: 12.7281
Epoch 713/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.7243
Epoch 714/2000
1/1 [===========

1/1 [==============================] - 0s 3ms/step - loss: 12.3927
Epoch 803/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.3891
Epoch 804/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.3855
Epoch 805/2000
1/1 [==============================] - 0s 4ms/step - loss: 12.3819
Epoch 806/2000
1/1 [==============================] - 0s 4ms/step - loss: 12.3782
Epoch 807/2000
1/1 [==============================] - 0s 4ms/step - loss: 12.3746
Epoch 808/2000
1/1 [==============================] - 0s 4ms/step - loss: 12.3710
Epoch 809/2000
1/1 [==============================] - 0s 4ms/step - loss: 12.3674
Epoch 810/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.3638
Epoch 811/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.3602
Epoch 812/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.3566
Epoch 813/2000
1/1 [==============================] - 0s 4ms/step - loss: 12.3530
Epoch 814/2000
1/1 [===========

1/1 [==============================] - 0s 4ms/step - loss: 12.0413
Epoch 903/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.0379
Epoch 904/2000
1/1 [==============================] - 0s 4ms/step - loss: 12.0344
Epoch 905/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.0311
Epoch 906/2000
1/1 [==============================] - 0s 4ms/step - loss: 12.0276
Epoch 907/2000
1/1 [==============================] - 0s 4ms/step - loss: 12.0242
Epoch 908/2000
1/1 [==============================] - 0s 4ms/step - loss: 12.0208
Epoch 909/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.0175
Epoch 910/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.0140
Epoch 911/2000
1/1 [==============================] - 0s 4ms/step - loss: 12.0107
Epoch 912/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.0073
Epoch 913/2000
1/1 [==============================] - 0s 4ms/step - loss: 12.0039
Epoch 914/2000
1/1 [===========

1/1 [==============================] - 0s 3ms/step - loss: 11.7107
Epoch 1003/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.7075
Epoch 1004/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.7043
Epoch 1005/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.7011
Epoch 1006/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.6979
Epoch 1007/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.6947
Epoch 1008/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.6915
Epoch 1009/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.6883
Epoch 1010/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.6851
Epoch 1011/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.6820
Epoch 1012/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.6788
Epoch 1013/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.6756
Epoch 1014/2000
1/1 

1/1 [==============================] - 0s 3ms/step - loss: 11.4058
Epoch 1101/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.4028
Epoch 1102/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.3998
Epoch 1103/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.3968
Epoch 1104/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.3937
Epoch 1105/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.3907
Epoch 1106/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.3877
Epoch 1107/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.3847
Epoch 1108/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.3817
Epoch 1109/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.3787
Epoch 1110/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.3757
Epoch 1111/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.3727
Epoch 1112/2000
1/1 

1/1 [==============================] - 0s 6ms/step - loss: 11.1185
Epoch 1199/2000
1/1 [==============================] - 0s 6ms/step - loss: 11.1157
Epoch 1200/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.1129
Epoch 1201/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.1100
Epoch 1202/2000
1/1 [==============================] - 0s 6ms/step - loss: 11.1072
Epoch 1203/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.1043
Epoch 1204/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.1015
Epoch 1205/2000
1/1 [==============================] - 0s 5ms/step - loss: 11.0987
Epoch 1206/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.0958
Epoch 1207/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.0930
Epoch 1208/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.0902
Epoch 1209/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.0873
Epoch 1210/2000
1/1 

1/1 [==============================] - 0s 3ms/step - loss: 10.8478
Epoch 1297/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.8451
Epoch 1298/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.8425
Epoch 1299/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.8398
Epoch 1300/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.8371
Epoch 1301/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.8344
Epoch 1302/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.8317
Epoch 1303/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.8291
Epoch 1304/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.8264
Epoch 1305/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.8237
Epoch 1306/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.8211
Epoch 1307/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.8184
Epoch 1308/2000
1/1 

1/1 [==============================] - 0s 4ms/step - loss: 10.5926
Epoch 1395/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.5901
Epoch 1396/2000
1/1 [==============================] - 0s 5ms/step - loss: 10.5875
Epoch 1397/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.5850
Epoch 1398/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.5825
Epoch 1399/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.5800
Epoch 1400/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.5775
Epoch 1401/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.5749
Epoch 1402/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.5724
Epoch 1403/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.5699
Epoch 1404/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.5674
Epoch 1405/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.5649
Epoch 1406/2000
1/1 

1/1 [==============================] - 0s 4ms/step - loss: 10.3519
Epoch 1493/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.3496
Epoch 1494/2000
1/1 [==============================] - 0s 2ms/step - loss: 10.3472
Epoch 1495/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.3448
Epoch 1496/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.3424
Epoch 1497/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.3400
Epoch 1498/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.3377
Epoch 1499/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.3353
Epoch 1500/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.3329
Epoch 1501/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.3305
Epoch 1502/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.3282
Epoch 1503/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.3258
Epoch 1504/2000
1/1 

1/1 [==============================] - 0s 4ms/step - loss: 10.1249
Epoch 1591/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.1227
Epoch 1592/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.1205
Epoch 1593/2000
1/1 [==============================] - 0s 5ms/step - loss: 10.1182
Epoch 1594/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.1160
Epoch 1595/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.1137
Epoch 1596/2000
1/1 [==============================] - 0s 5ms/step - loss: 10.1115
Epoch 1597/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.1092
Epoch 1598/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.1070
Epoch 1599/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.1048
Epoch 1600/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.1025
Epoch 1601/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.1003
Epoch 1602/2000
1/1 

1/1 [==============================] - 0s 3ms/step - loss: 9.9087
Epoch 1690/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.9065
Epoch 1691/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.9044
Epoch 1692/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.9023
Epoch 1693/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.9002
Epoch 1694/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.8980
Epoch 1695/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.8960
Epoch 1696/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.8938
Epoch 1697/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.8917
Epoch 1698/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.8896
Epoch 1699/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.8875
Epoch 1700/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.8854
Epoch 1701/2000
1/1 [===========

1/1 [==============================] - 0s 4ms/step - loss: 9.7027
Epoch 1790/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.7007
Epoch 1791/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.6987
Epoch 1792/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.6967
Epoch 1793/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.6947
Epoch 1794/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.6927
Epoch 1795/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.6907
Epoch 1796/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.6887
Epoch 1797/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.6867
Epoch 1798/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.6847
Epoch 1799/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.6827
Epoch 1800/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.6807
Epoch 1801/2000
1/1 [===========

1/1 [==============================] - 0s 4ms/step - loss: 9.5084
Epoch 1890/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.5065
Epoch 1891/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.5047
Epoch 1892/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.5028
Epoch 1893/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.5009
Epoch 1894/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.4990
Epoch 1895/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.4971
Epoch 1896/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.4952
Epoch 1897/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.4934
Epoch 1898/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.4915
Epoch 1899/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.4896
Epoch 1900/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.4878
Epoch 1901/2000
1/1 [===========

1/1 [==============================] - 0s 4ms/step - loss: 9.3253
Epoch 1990/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.3235
Epoch 1991/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.3217
Epoch 1992/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.3199
Epoch 1993/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.3182
Epoch 1994/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.3164
Epoch 1995/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.3146
Epoch 1996/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.3128
Epoch 1997/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.3111
Epoch 1998/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.3093
Epoch 1999/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.3075
Epoch 2000/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.3058


In [14]:
# Ask my score
print("Your score will be ", tf.model.predict([[100, 70, 101]]))

Your score will be  [[195.89542]]


In [15]:
# Ask score
print("Other scores will be ", tf.model.predict([[60, 70, 110], [90, 100, 80]]))

Other scores will be  [[175.86897]
 [173.34227]]
